### ISSUE TITLE
Can not find some css file

### ISSUE THREAD

**Issue by EthanLXGu** [GeekaholicLin/hexo-theme-ylion#1]
GET http://localhost:4000/css/pages/article-exp.css 
localhost/:33 GET http://localhost:4000/css/base.css 
app.js:358 Uncaught ReferenceError: AV is not defined
    at app.js:358
    at app.js:373
    at window.onload (app.js:376)

When I use your theme, I got these errors, so many large words and no format, can you help me solve this issue? Thanks.

**Comment by GeekaholicLin** [comment]
It seems that you did not  use the leancloud correctly if you got the error in your browser.Can your paste your theme config?Just part of the leancloud config as followings.If you do not have a leancloud,you can register one or disable the leancloud.

```yaml
leancloud:
  enable: true
  className: "BlogCounter"
  app_id:
  app_key:
  region:
  limits: 10 

leancloud_src: http://cdn1.lncld.net/static/js/2.1.0/av-min.js
```
