### ISSUE TITLE
加上 leancloud 的 app id 和 key 之後，瀏覽數字還是轉圈圈

### ISSUE THREAD

**Issue by mosdeo** [GeekaholicLin/hexo-theme-ylion#25]
```
leancloud:
  enable: true
  className: "BlogCounter"
  app_id: a0vxRDRolcllDSWWbstYjMet-gzGzoHsz
  app_key: lqFfEzLnBmeOgS1XoRjA9XoY
  region:
  limits: 10
```
使用後，leancloud.cn 後台有出現 BlogCounter 的 API 請求數增加，但是數據為空。
http://localhost:4000/ 可以正常運作，leancloud.cn 後台可以看到紀錄，但發佈到 github 上面就不行。
