### ISSUE TITLE
可以部分文章指定縮圖嗎？

### ISSUE THREAD

**Issue by mosdeo** [GeekaholicLin/hexo-theme-ylion#39]
目前縮圖是從文章裡隨機挑選，但是有些文章我會想要指定縮圖，讓讀者在預覽階段就比較有"感覺"。這是我很想要的功能，請問目前有辦法做到嗎？
## **這個功能我願意打賞 1000 TWD** 給@GeekaholicLin

**Comment by GeekaholicLin** [comment]
这个功能实现了的，我一翻issue，看到类似的issue #24 也是你提出的 😂 

> 规则:Front-matter中的自定义'img'字段 > 文章内的图片(随机获取) > defaultImgs(随机获取) 【来自README】

你看看是不是你需要的~

PS: 你倒是提醒了我还有一个bug没修 😂

**Comment by mosdeo** [comment]
但目前已經實現的是全局設定吧？ 我是希望可以個別文章指定選擇哪一個縮圖，最好在原始的 markdown 裡面就可以指定。

2017年10月13日 09:29，"noone" <notifications@github.com>寫道：

**Comment by GeekaholicLin** [comment]
不不不，不是的，你可以像添加文章title一样添加**img**即可实现：

``` yaml
---
title: AMD等模块化的简单原理
img: http://example.com/xxx.jpg
---
```
