### ISSUE TITLE
评论框无法初始化

### ISSUE THREAD

**Issue by tidyjiang8** [GeekaholicLin/hexo-theme-ylion#8]
你好

我的gitment配置如下：
```
gitment:
  enable: true
  owner: tidyjiang8
  repo: tidyjiang8.github.io
  client_id: 87e70869759a2eb97020
  client_secret: d2c9da2115c778a45072b1b485763d7a5a5851ce
  labels: "blog,gitment"
  perPage: 20
  maxCommentHeight:
```
创建应用时的参数如下：
```
Client ID
    87e70869759a2eb97020
Client Secret
    d2c9da2115c778a45072b1b485763d7a5a5851ce
Homepage URL
    https://tidyjiang8.github.io/
Authorization callback URL
    https://tidyjiang8.github.io/
```
但是在评论框中，Login授权后，无法初始化。评论框地址是： 
- [https://tidyjiang8.github.io/2017/06/19/hello-world/#comments](https://tidyjiang8.github.io/2017/06/19/hello-world/#comments)

不知道哪里出了问题，需求帮助~~
